<a href="https://colab.research.google.com/github/KeerthanaSistla/Python-for-Data-Analysis-Visualization/blob/main/Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd

In [2]:
countries_excel = pd.read_excel('top_10_countries.xls', sheet_name='data')

In [3]:
countries_excel.head()

   Rank Country / Dependency    Region  Population  % of world       Date
0     1                China      Asia  1412600000      0.1780 2021-12-31
1     2                India      Asia  1386946912      0.1750 2022-01-18
2     3        United States  Americas   333073186      0.0420 2022-01-18
3     4            Indonesia      Asia   271350000      0.0342 2020-12-31
4     5             Pakistan      Asia   225200000      0.0284 2021-07-01

In [4]:
countries_csv = pd.read_csv('top_10_countries.csv')

In [5]:
countries_csv.head()

   Rank Country / Dependency    Region  Population % of world       Date
0     1                China      Asia  1412600000     17.80%  31-Dec-21
1     2                India      Asia  1386946912     17.50%  18-Jan-22
2     3        United States  Americas   333073186      4.20%  18-Jan-22
3     4            Indonesia      Asia   271350000      3.42%  31-Dec-20
4     5             Pakistan      Asia   225200000      2.84%  01-Jul-21

#Output

In [6]:
countries_out = countries_excel.pivot_table(index='Region', values='Population', aggfunc='sum')

In [7]:
countries_out

          Population
Region
Africa     211401000
Americas   673318851
Asia      3468159488
Europe     146171015

In [12]:
countries_out.to_csv(r'C:\Users\Sistla Keerthana\Downloads\Course Resurces-Python for Data Analysis and Visualization\Course Resurces-Python for Data Analysis and Visualization\11 Data Sources\01 Excel and CSV')